In [14]:
from src.features import build_training_features
df = build_training_features()

✓ Built 15,844 training samples with 34 features

In [24]:
df.to_csv("data/training_features.csv", index=False)

In [25]:
import pandas as pd
df = pd.read_csv("data/training_features.csv")

In [26]:
df.shape

(15844, 34)

In [27]:
df.tail(10)

,date,home_team,away_team,tournament,neutral,target,home_ranking,away_ranking,ranking_diff,home_elo,...,away_form_gf,away_form_ga,away_form_gd,h2h_matches,h2h_home_wins,h2h_away_wins,h2h_draws,home_days_rest,away_days_rest,is_world_cup
15834,2026-06-16,France,Senegal,FIFA World Cup,1,HOME,1.0,14.0,13.0,2081.0,...,7,7,0,2,0,2,0,8,7,1
15835,2026-06-16,Iraq,Norway,FIFA World Cup,1,AWAY,61.0,44.0,-17.0,1607.0,...,9,5,4,0,0,0,0,7,9,1
15836,2026-06-17,England,Croatia,FIFA World Cup,1,HOME,4.0,11.0,7.0,2020.0,...,8,9,-1,10,6,3,1,7,10,1
15837,2026-06-17,Ghana,Panama,FIFA World Cup,1,HOME,65.0,53.0,-12.0,1503.0,...,10,11,-1,0,0,0,0,15,11,1
15838,2026-06-17,Portugal,Congo DR,FIFA World Cup,1,DRAW,5.0,51.0,46.0,1984.0,...,4,3,1,0,0,0,0,7,8,1
15839,2026-06-17,Uzbekistan,Colombia,FIFA World Cup,1,AWAY,62.0,13.0,-49.0,1727.0,...,10,6,4,0,0,0,0,9,10,1
15840,2026-06-18,Mexico,South Korea,FIFA World Cup,0,HOME,15.0,25.0,10.0,1860.0,...,8,6,2,10,5,2,3,7,7,1
15841,2026-06-18,Switzerland,Bosnia and Herzegovina,FIFA World Cup,1,HOME,19.0,52.0,33.0,1889.0,...,4,4,0,1,0,1,0,5,6,1
15842,2026-06-18,Czech Republic,South Africa,FIFA World Cup,1,DRAW,41.0,60.0,19.0,1726.0,...,3,5,-2,1,0,0,1,7,7,1
15843,2026-06-18,Canada,Qatar,FIFA World Cup,0,HOME,30.0,35.0,5.0,1784.0,...,2,6,-4,1,1,0,0,6,5,1

In [28]:
df.head()

,date,home_team,away_team,tournament,neutral,target,home_ranking,away_ranking,ranking_diff,home_elo,...,away_form_gf,away_form_ga,away_form_gd,h2h_matches,h2h_home_wins,h2h_away_wins,h2h_draws,home_days_rest,away_days_rest,is_world_cup
0,2010-01-02,Iran,North Korea,Friendly,1,HOME,21.0,NaN,NaN,1760.0,...,11,4,7,10,8,0,2,3,3,0
1,2010-01-02,Qatar,Mali,Friendly,0,DRAW,35.0,NaN,65.0,1425.0,...,6,5,1,0,0,0,0,3,3,0
2,2010-01-02,Syria,Zimbabwe,Friendly,1,HOME,NaN,NaN,0.0,NaN,...,7,7,0,0,0,0,0,3,4,0
3,2010-01-02,Yemen,Tajikistan,Friendly,0,AWAY,NaN,NaN,0.0,NaN,...,7,11,-4,1,1,0,0,3,3,0
4,2010-01-03,Angola,Gambia,Friendly,1,DRAW,NaN,NaN,NaN,NaN,...,5,2,3,0,0,0,0,4,180,0

In [29]:
df.columns

Index(['date', 'home_team', 'away_team', 'tournament', 'neutral', 'target',
       'home_ranking', 'away_ranking', 'ranking_diff', 'home_elo', 'away_elo',
       'elo_diff', 'home_squad_age', 'away_squad_age', 'home_market_value',
       'away_market_value', 'market_value_ratio', 'home_form_win_rate',
       'home_form_pts_rate', 'home_form_gf', 'home_form_ga', 'home_form_gd',
       'away_form_win_rate', 'away_form_pts_rate', 'away_form_gf',
       'away_form_ga', 'away_form_gd', 'h2h_matches', 'h2h_home_wins',
       'h2h_away_wins', 'h2h_draws', 'home_days_rest', 'away_days_rest',
       'is_world_cup'],
      dtype='object')

In [30]:
print(len(df.columns))

34